---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orc-controller-manager
  namespace: orc-system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: http_proxy
          value: ""
        - name: https_proxy
          value: ""
        - name: no_proxy
          value: ""
