apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k-orc.fullname" . }}-image-editor-role
  labels:
  {{- include "k-orc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images/status
  verbs:
  - get
