apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k-orc.fullname" . }}-manager-role
  labels:
  {{- include "k-orc.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - flavors
  - floatingips
  - images
  - networks
  - ports
  - projects
  - routerinterfaces
  - routers
  - securitygroups
  - servergroups
  - servers
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - flavors/status
  - floatingips/status
  - images/status
  - networks/status
  - ports/status
  - projects/status
  - routerinterfaces/status
  - routers/status
  - securitygroups/status
  - servergroups/status
  - servers/status
  - subnets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k-orc.fullname" . }}-manager-rolebinding
  labels:
  {{- include "k-orc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "k-orc.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "k-orc.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
